# Project Structure

Customer_Feedback_Analysis/
│
|---Customer Feedback Analysis and Automated Response using Python & Generative AI.ipynb
|--- Amazon_Reviews.csv
|--- README.md

# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")
import re
from collections import Counter

# Load Dataset

In [2]:
df=pd.read_csv("C:\\Users\\Client\\Assessment_project\\Amazon_Reviews.csv", engine='python')

# Check the dataset.

In [3]:
df.head(1)

,Reviewer Name,Profile Link,Country,Review Count,Review Date,Rating,Review Title,Review Text,Date of Experience
0,Eugene ath,/users/66e8185ff1598352d6b3701a,US,1 review,2024-09-16T13:44:26.000Z,Rated 1 out of 5 stars,A Store That Doesn't Want to Sell Anything,"I registered on the website, tried to order a ...","September 16, 2024"

In [4]:
df.shape

(21214, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21214 entries, 0 to 21213
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Reviewer Name       21214 non-null  object
 1   Profile Link        21163 non-null  object
 2   Country             21054 non-null  object
 3   Review Count        21055 non-null  object
 4   Review Date         21055 non-null  object
 5   Rating              21055 non-null  object
 6   Review Title        21055 non-null  object
 7   Review Text         21055 non-null  object
 8   Date of Experience  20947 non-null  object
dtypes: object(9)
memory usage: 1.5+ MB

In [6]:
df.columns

Index(['Reviewer Name', 'Profile Link', 'Country', 'Review Count',
       'Review Date', 'Rating', 'Review Title', 'Review Text',
       'Date of Experience'],
      dtype='object')

Expected columns are

Reviewer Name
Profile Link
Country
Review Count
Review Date
Rating
Review Title
Review Text
Date of Experience

# Data Cleaning

Missing values

In [7]:
df.isnull().sum()

Reviewer Name           0
Profile Link           51
Country               160
Review Count          159
Review Date           159
Rating                159
Review Title          159
Review Text           159
Date of Experience    267
dtype: int64

Fill missing review text.

In [8]:
df["Review Text"] = df["Review Text"].fillna("No Review")

Remove rows where Rating is missing.

In [9]:
df = df.dropna(subset=["Rating"])

In [10]:
df = df.dropna(subset=["Date of Experience"])

In [11]:
df = df.dropna(subset=["Country"])

In [12]:
df.isnull().sum()

Reviewer Name         0
Profile Link          0
Country               0
Review Count          0
Review Date           0
Rating                0
Review Title          0
Review Text           0
Date of Experience    0
dtype: int64

Convert Rating into Numbers

Ratings are stored like

Rated 1 out of 5 stars
Rated 5 out of 5 stars

In [13]:
df["Rating"] = df["Rating"].str.extract("(\d)").astype(int)

In [14]:
df["Rating"].value_counts()

Rating
1    13120
5     4447
4     1278
2     1227
3      874
Name: count, dtype: int64

# Clean Review Text

Creating cleaning function.

In [15]:
def clean_text(text):

    text = text.lower()

    text = re.sub(r"[^a-zA-Z\s]", "", text)

    text = re.sub(r"\s+", " ", text)

    return text.strip()

Apply it.

In [16]:
df["Clean_Review"] = df["Review Text"].apply(clean_text)

df[["Review Text","Clean_Review"]].head()

,Review Text,Clean_Review
0,"I registered on the website, tried to order a ...",i registered on the website tried to order a l...
1,Had multiple orders one turned up and driver h...,had multiple orders one turned up and driver h...
2,I informed these reprobates that I WOULD NOT B...,i informed these reprobates that i would not b...
3,I have bought from Amazon before and no proble...,i have bought from amazon before and no proble...
4,If I could give a lower rate I would! I cancel...,if i could give a lower rate i would i cancell...

# Rule-Based Filtering



Critical Reviews = 1-star and 2-star reviews.

In [17]:
critical_reviews = df[df["Rating"] <= 2]

critical_reviews.shape

(14347, 10)

Display a few reviews.

In [18]:
critical_reviews[["Rating","Review Title","Review Text"]].head()

,Rating,Review Title,Review Text
0,1,A Store That Doesn't Want to Sell Anything,"I registered on the website, tried to order a ..."
1,1,Had multiple orders one turned up and…,Had multiple orders one turned up and driver h...
2,1,I informed these reprobates,I informed these reprobates that I WOULD NOT B...
3,1,Advertise one price then increase it on website,I have bought from Amazon before and no proble...
4,1,If I could give a lower rate I would,If I could give a lower rate I would! I cancel...

# Complaint Keyword Analysis

Creating stop words.

In [19]:
stop_words = {
    "the","and","this","that","with","have","from",
    "they","their","been","were","would","there",
    "about","your","very","when","what","into",
    "after","before","because","could","should",
    "amazon","review","stars","star","product",
    "service","order","customer"
}

Creating keyword function.

In [32]:
def top_keywords(texts, top_n=20):

    words = []

    for review in texts:

        for word in review.split():

            if len(word) > 3 and word not in stop_words:
                words.append(word)

    return Counter(words).most_common(top_n)

In [33]:
keywords = top_keywords(critical_reviews["Clean_Review"])

keywords

[('them', 6643),
 ('delivery', 6230),
 ('will', 6135),
 ('account', 4908),
 ('time', 4899),
 ('item', 4674),
 ('prime', 4488),
 ('refund', 4482),
 ('just', 4367),
 ('dont', 4347),
 ('then', 4046),
 ('never', 3898),
 ('money', 3736),
 ('even', 3647),
 ('back', 3607),
 ('items', 3569),
 ('delivered', 3442),
 ('again', 3384),
 ('told', 3282),
 ('days', 3267)]

Expected Output

[('them', 6643),
 ('delivery', 6230),
 ('will', 6135),
 ('account', 4908),
 ('time', 4901),
 ('item', 4676),
 ('prime', 4488),
 ('refund', 4482),
 ('just', 4370),
 ('dont', 4347),
 ('then', 4046),
 ('never', 3898),
 ('money', 3736),
 ('even', 3648),
 ('back', 3607),
 ('items', 3569),
 ('delivered', 3442),
 ('again', 3384),
 ('told', 3282),
 ('days', 3267)]

# Select Three Critical Reviews

In [34]:
critical_reviews["Length"] = critical_reviews["Review Text"].str.len()

top3 = critical_reviews.sort_values(
    by="Length",
    ascending=False
).head(3)

top3[["Rating","Review Title","Review Text"]]

,Rating,Review Title,Review Text
17974,1,ANTI-SEMITIC CLUB COMPANY: Unethical and Not P...,This company has disabled merchants for absolu...
18045,1,AMAZON RUINED MY CHRISTMAS - DO NOT TRUST AMAZ...,In relation to Order # 205-8187368-2071530:On ...
15792,1,My Honest Opinion About Amazon.com!,My honest opinion.I have been an Amazon Prime ...

# Generative AI

Install

In [23]:
!pip install google-generativeai

Requirement already satisfied: google-generativeai in c:\users\client\anaconda3\lib\site-packages (0.8.6)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in c:\users\client\anaconda3\lib\site-packages (from google-generativeai) (0.6.15)
Requirement already satisfied: google-api-core in c:\users\client\anaconda3\lib\site-packages (from google-generativeai) (2.33.0)
Requirement already satisfied: google-api-python-client in c:\users\client\anaconda3\lib\site-packages (from google-generativeai) (2.198.0)
Requirement already satisfied: google-auth>=2.15.0 in c:\users\client\anaconda3\lib\site-packages (from google-generativeai) (2.56.2)
Requirement already satisfied: protobuf in c:\users\client\anaconda3\lib\site-packages (from google-generativeai) (5.29.6)
Requirement already satisfied: pydantic in c:\users\client\anaconda3\lib\site-packages (from google-generativeai) (2.12.4)
Requirement already satisfied: tqdm in c:\users\client\anaconda3\lib\site-packages (from google-generativeai) (4.67.1)
Requirement already satisfied: typing-extensions in c:\users\client\anaconda3\lib\site-packages (from google-generativeai) (4.15.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in c:\users\client\anaconda3\lib\site-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.28.2)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in c:\users\client\anaconda3\lib\site-packages (from google-api-core->google-generativeai) (1.75.0)
Requirement already satisfied: requests<3.0.0,>=2.33.0 in c:\users\client\anaconda3\lib\site-packages (from google-api-core->google-generativeai) (2.34.2)
Requirement already satisfied: grpcio<2.0.0,>=1.41.0 in c:\users\client\anaconda3\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.83.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.41.0 in c:\users\client\anaconda3\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\client\anaconda3\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\client\anaconda3\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (46.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\client\anaconda3\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core->google-generativeai) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\client\anaconda3\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core->google-generativeai) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\client\anaconda3\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core->google-generativeai) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\client\anaconda3\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core->google-generativeai) (2026.5.20)
Requirement already satisfied: cffi>=2.0.0 in c:\users\client\anaconda3\lib\site-packages (from cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (2.0.0)
Requirement already satisfied: pycparser in c:\users\client\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (2.23)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\client\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.1)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in c:\users\client\anaconda3\lib\site-packages (from google-api-python-client->google-generativeai) (0.32.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in c:\users\client\anaconda3\lib\site-packages (from google-api-python-client->google-generativeai) (0.4.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in c:\users\client\anaconda3\lib\site-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: pyparsing<4,>=3.1 in c:\users\client\anaconda3\lib\site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.5)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\client\anaconda3\lib\site-packages (from pydantic->google-generativeai) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\client\anaconda3\lib\site-packages (from pydantic->google-generativeai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\client\anaconda3\lib\site-packages (from pydantic->google-generativeai) (0.4.2)
Requirement already satisfied: colorama in c:\users\client\anaconda3\lib\site-packages (from tqdm->google-generativeai) (0.4.6)

Import

In [24]:
import google.generativeai as genai

API Key
Check if you actually have a Gemini API key

Go to:

https://aistudio.google.com/app/apikey

Sign in with your Google account.
Click Create API Key.
Copy the key.

In [25]:
genai.configure(api_key="Enter API Key")

Model

In [26]:
model = genai.GenerativeModel("models/gemini-3.6-flash")

Function

In [38]:
def generate_email(review):

    prompt = f"""
You are a professional customer support executive.

Write a short apology email.

Customer Review:
{review}

The email should

- apologize
- acknowledge the issue
- sound empathetic
- promise improvement
- be under 150 words.
- include Gagan Kumar J K in the place of your name
"""

    response = model.generate_content(prompt)

    return response.text

Generate emails.

In [28]:
for i, review in enumerate(top3["Review Text"],1):

    print("="*60)

    print("Review",i)

    print(review)

    print()

    print(generate_email(review))

    print("\n")

============================================================
Review 1
This company has disabled merchants for absolutely no reason; My family and multiple businesses are Jewish run, this is our story.  That is right, Amazon and Amazon Pay, are both anti Semitic company's. So, if you are jewish, as I am and my mother;  had her beauty salon on the Amazon account. They harassed her for "Selling Drugs or Adult Services", which was a major insult, as she was working on her new design for selling retail products for her beauty salon. Towne Plaza Hair studio has been in business for 29 years! I have been in business about ten years now and we both have never had a charge back nor refund. They have their User Agreements and every right to "part company for no reason", but the both of us followed every rule and guideline, they looked for anything they could discriminate against when doing their reviews. Our new site looks so nice and clean, so we will get to make money than ever and it is best to not put your money in company's that are this dishonest and hate filled. That is the one thing I want to really get through to people, when companies start out, they start from Humble beginnings; now this company was designed by elites to make it, so it would never fail. The royals use this to control what other LLC or Corporations are doing. They discriminate against small business owners, and don't want to give the little guy a chance, they are like Brokers and like getting loans from a bank. They shouldn't though, you should be given a fair chance to make money like the rest. They didn't like that my Mother made 700 dollars the first week selling her Certified and verified beauty retail products, which she gets from Sally's. So no, my mother and myself aren't selling anything illegal or anything that another company wouldn't sell. So, if you are a Merchant and you have a company like this, they are just as bad as Paypal and Square. The thing you must think about is sending your money to them for their services or even just the Sales tax fees. DO YOU WANT TO GIVE YOUR HARD EARNED MONEY To Bullies that scam people out of their money, if they don't like you, simply because you are Jewish. They let the both of us sell from our website, before they profiled and prejudged us for being a Jewish proud heritage company. You should be able to promote whatever Ethnicity that you are with your business, and even religious view, if you want. We don't encourage any spiritual belief system, but mainly a health promoting company. This is the other thing they don't like, because they rather you be sick and just go to the doctor and get on medications. So, they get write off's for cutting the throats of small businesses, who do sell or focus on healthier products. See, because they themselves want to keep the competition in their ballpark with the Mass Production corporations and LLC's. Even if your company follows every single rule and user agreement guideline, as the both of us did. My mother would email them and tell them that she sent in every piece of paperwork they would request, after making her jump through firey hoops. Asking for her ID, Social Security or EIN number, Bank statement after Bank statement, Proof of her business location, with Pictures of all of this, and just on and on. IT WAS BAD. They pretty much the both of us, were making money and freezing our account, so we wouldn't have access to our profits before they finally decide to close our accounts with NO APPEAL and Hold on to all our money for 180 Days. This is also ILLEGAL And the same thing that the other unethical frauds such as PayPal  & Square  are doing. They began to investigate us, by typing our emails into Facebook and this is where the prejudice starts. They will review you with Audits, simply if they don't like you or your company, because you are say Jewish by blood, then they will come up with some lie to why they aren't going to Reinstate your company. Either these auditor, special-mystery customers have too much time, or they are really doing a great job at taking the ease away from using their applications, that some company's require you to use. Say, you don't want to use PayPal or Square and in some circumstances you are forced to use this company. This is similar to Net Neutrality, but it is more like Sole Prop. Racism.Again, both of our Company's have been around longer than all these phony card processor company's and they can look up our 10/10 reviews, with no refunds or charge backs ever. This sort of stress for small business owners, and then freezing and holding profits from sales that you already processed and shipped out, can cause a small business to go under and completely sink. I feel that is the entire goal for Large totalitarian corporations such as this. They didn't want us to make money using their platform, we don't fit their specific qualifications, but we follow every single one of their rules and user agreements, we don't sell products that are illegal nor do activities that are criminal, but they truly are the criminal ones, for they are discriminating and hating with out cause. When you have a crystal clear record and no blemishes, its hard for them to come up with any excuses to how they aren't judging our company's for simply being Jewish. Since they want to turn us away,I would say out of respect towards another Hard Working, Honest, and Ethical Company, such as myself and my mother, and most likely many many more,this. Out of respect DO NOT USE THIS COMPANY EVER, TURN AWAY FROM THEM BEFORE THEY TURN YOU DOWN. If you already have Amazon Pay, Just be the Bigger and Better Person, since they are stuck up and arrogant themselves (Which is Unprofessional).Cancel your Amazon Pay or Merchant account, and find a real good business that knows what they are doing. There are many cart processor company's out there, and you don't need amazon for selling your products.They are far too overpriced and because they road run over company's like myself and my mother, they won't last much longer. This will all come back on them, so I hope they live up their extravagant Superior Entitlement role. Since they think they are a great company, Read other Reviews, I am not the only Merchant that has been mistreated and unrightfully and unethically discriminated and judged. This will come back at them right now. *If you need to sell your products, I would say go to a real company such as CLICK FUNNELS, and sell your products with them, so you don't have to cut your profits with a Unethical company like Amazon. Sincerely you will make alot more money with this ClickFun, and they have a university that shows you how to use it, and you will funnel far more customers than Amazon. This company will be taking Amazon out soon, because they do know how to be honest and ethical. They Would never judge a person for being Jewish and then make up a bunch of weird charges or accusations about you. For instance they told my mom that she shouldn't sell "Drug Paraphalia or Drugs, or Adult Services and Products". This was not funny at all, as my mother is a 67 year old woman that has been in business over 29 years and never ever sold such things. Very insulting and we are very baffled why they would even say such things in the email. If people want to know what the email said, just let me know, I can prove they actually said This.So again, we didn't sell anything that was Illegal, or against the law or against guidelines. We resell products that are Certified Organic and at Beauty Retail warehouses.So, how can we be doing anything wrong, if we both make over 20,000 Dollars in sales, when operating smoothly; but they can or will also shut you down, if you make less profits that this. This is also another form of discrimination. I don't usually do things like this, but this review is sacred to me, as I believe the world does need to know the true truth as it is unadulterated. Maybe Amazon is selling drugs and laundering money for sell services or products themselves. Who knows, I believe since they like to discriminate and misjudge people and company's, perhaps they have something to hide themselves. I know any company that freezes your account for 180 days, is already committing an illegal fraud, where they are holding money to draw interest off your profits. There is no reason you need to wait a whole six months," to make sure that you can cover a chargeback refund". Problem is we didn't get paid and the customers got their product. You are left having to issue your client a refund and figure out how to process their order again. This makes you look unprofessional, when Amazon was the one's who made the mistake. Truly, if they are doing things like this, I am sure that at the top, they might be hiding another elaborate conspiracy, such as illegal activities, or maybe even Human trafficking or other Criminal acts. Maybe that's why they can't have such honest and enlightened people, it would mess up the dark things this company really stands for. Don't go with Amazon, Cancel Your Account; You don't Need them, that's the  smartest choice to do. I will also be making this public with the Media and many high up Networks I am affiliated with, that has over 2 Billion plus people and affluent business owners and other influential people. We will be making a blog about all these things and emails that went along with our Unfair and Illegal experience. I know most likely they will reply with some, "This is our policy rules and guidelines, that we can part company for absolutely any reason" post below this review. That is perfectly correct and you can, AND I can use the heavy influence and Power to sway people far from your Crooked and lying company.  I Guess it is true truth, what they say about when you get too big for yourself, you start becoming the bad guy's. I knew Amazon, when they started off as a company, they were very humble, honest and would never allow BAD to happen. Now, are they GOD?

Dear Merchant,

I am deeply sorry for the distress and frustration you and your mother experienced regarding your account suspensions and frozen funds.

We take concerns about unfair treatment and account misclassifications very seriously. Hearing that your established beauty studio faced offensive accusations and sudden account restrictions is deeply concerning, and I sincerely apologize for the pain and disruption this situation caused your family and businesses. We stand firmly against discrimination of any kind.

I have escalated your feedback directly to our leadership team to investigate how your accounts were handled and to ensure our verification processes are conducted with fairness, accuracy, and respect. We promise to use your experience to make meaningful improvements to our merchant review systems and prevent this from happening again.

Thank you for bringing this to our attention.

Sincerely,
Gagan Kumar J K
Customer Support Executive


============================================================
Review 2
In relation to Order # 205-8187368-2071530:On 18th December I placed an order with Amazon for around £250 worth of items using their Prime 'Guaranteed Next Day' delivery service. The order consisted 11 different items (a range of toys and other gifts bought for Christmas to give to family and friends). Amazon in the past have been a very reliable and reputable company with exemplary customer service so I felt that this was a convenient and safe option to make sure I had everything arrive in time for Christmas. This, however, was the start of my Christmas nightmare.The following day, nothing arrived. This was not an issue however, as my family were not coming to visit until the following Saturday so there was still another 4 days left before it would present any sort of problem for me. On the Wednesday, 3 of the 11 items turned up. On Thursday, nothing. On Friday morning, I finally receive a phone call from my sister (whose address the parcels were due to arrive at) telling me she was starting to get worried as most of the items had still not arrived and they had to be ready and wrapped for the following day to give to my visiting family members who live in a different part of the country. Given the urgency of the situation, I decided to take a break from work and give Amazon's customer service department a call.I initially spoke to a member of their team who looked into the situation and found that the items had indeed not been delivered, but that it should be fine and they would most likely arrive later that day. I explained my situation to them and told them that essentially if the items did not turn up I would be stuck with nothing to give to my family to open on Christmas day. I asked this member of staff to look into the situation again so that they could absolutely guarantee this, at which point the line goes quiet and a few seconds later the call terminates. Not being satisfied with the outcome, I decide to call back again at which point I get through to another customer service agent who again appears to hang up the call. By this point I was getting very frustrated but given that I had no choice I decided to call them again.By this time, it was 3:00pm and I had already wasted around half an hour of my working day trying to sort the situation out. I then get through to customer service agent number 3, who I explain to that I haven't received my items - to which he replies that they will definitely arrive by 9pm that night. I then explain to the agent that I need this absolutely guaranteed as if they do not deliver the items by 9pm I would then not have an opportunity to go out Christmas shopping that day in order to replace the items they had not delivered. After some deliberation he agrees to go and double check for me, and, surprise surprise, he tells me that the parcels won't be arriving after all.By this point, I was absolutely fuming. I could not believe that after 5 days of waiting on their 'Guaranteed Next Day' delivery and an hour on the phone speaking to 3 different people they were actually telling me they were not able to deliver my parcels. All of this given that they DIDN'T EVEN HAVE THE DECENCY to contact me and let me know what was going on. Had my sister not bothered to contact me, I wouldn't have even known until the following day (by which point it would be too late).Anyway, I continued my conversation with agent number 3 and explained that I was absolutely disgusted by their level of service and that my only option was to finish work early (costing me around £50 in lost pay), travel to the town centre and spend the rest of my afternoon/evening shopping for presents that I didn't have the money for (since I had already spent it with Amazon). The initial response to this was to offer me a £5 Amazon gift card and 1 month free Amazon Prime (frankly an insult given the situation). They then offer me a refund to which I tell the agent it does not compensate me for the situation they have caused and I would be making a complaint and closing down my account (which I have had for over 10 years and spent many thousands of pounds with them on). He then decides to go and speak to his manager, and agrees that they will still fulfill the order and I will receive the items in due course, and they will issue me a full refund (which would instantly arrive in my account) for the items not yet received. Although I was not happy about having to leave work and roam around the town centre buying presents, I felt this was fair compensation and the best they could do given the situation. We then end the call and I head out of work.I arrive in a very busy town centre and attempt to look for anything which may be suitable given the money I had on my card. I enter Toys R Us and grab some toys for my niece and nephew, head to the counter and get my card out to pay. I enter my PIN and find that my card has been declined. I then try again, but it appears as though there is no money in my account. I then leave Toys R Us (the time is now about 5:00pm) and head to the Cashpoint machine to find that my refund has not yet arrived. I go on Amazon's live chat and the person I speak to tells me that the refund will arrive in 5-7 working days. Desperate, I call one of my friends who agrees to lend me £50 (not exactly enough for 8 gifts but better than nothing). I then spend my evening around town buying anything I can so at least there is something for my family to open for Christmas (aware that the items should arrive later on and I could always try and post them later).Christmas then comes and goes without too much bother. It comes to my attention in the first week of January however that the items had still not been delivered, so I decide its time to give Amazon another call. I get through to a customer service agent, and after saying a few words the call hangs up, so I call back again. I then get through to another agent who explains to me that my refund has been issued. I tell him that I have received the refund but I was still waiting for the items, for which he says the items had been returned and would not be sent out again. I then explain to them that I was still supposed to receive the items as per the agreement I made with them on the 22nd of December, to which he replies (surprise) that there are no notes on the system to this effect. He agrees to raise the issue with a manager for it to be investigated and I would definitely receive an email back about this in 5-7 days.2 weeks later, I still have no email or items, so I call Amazon again. After calling them three times and being hung up on and spending around 45 minutes on the phone I am finally put through to a supervisor. They tell me again that there is no notes on the system and there has been no investigation into my case. This time, I am promised a call back the following day at 5:00pm once the investigation has been done. I sit next to my phone at 5:00pm the following day but do not receive a call. I then check my Amazon account to find a message sent saying that they 'weren't able to reach me' and they were sorry that I was 'misinformed' that I would still receive the items. They tell me I should call back again for more information about it.I can tell you I have now given up trying to deal with their shambolic customer service team. The entire experience has been absolutely disgraceful and they should be ashamed of the way they have treated me as a longstanding and loyal customer of 10 years. I am now going to be closing my account with them and I will be posting my experience on every major review site online as well as telling all my friends and family. Amazon has embarrassed me at a supposed happy time of year and they don't seem to give a monkeys about their customers anymore. I will now be reporting them to the Advertising Standards Agency regarding their false advertising claims and I will be speaking to BBC's Watchdog about my case.I HAVE FULL EVIDENCE FOR ALL OF THIS BUT IF ANYONE ELSE HAS HAD A SIMILAR EXPERIENCE PLEASE LET ME KNOW AS WE CAN POTENTIALLY WORK TOGETHER IN HOLDING AMAZON TO ACCOUNT ON THEIR FALSE CLAIMS AND POOR CUSTOMER SERVICE.

Subject: Sincere Apologies Regarding Order # 205-8187368-2071530

Dear Customer,

Please accept my sincere apologies for the immense frustration and distress caused regarding Order # 205-8187368-2071530. As a loyal customer of 10 years, you deserved a seamless experience, especially during Christmas, not the ordeal you endured.

I am deeply sorry for the failed delivery, disconnected calls, misinformation, and broken promises regarding your refund and call-backs. It is heartbreaking to hear how this impacted your holiday season and caused financial strain. We completely failed you.


In [29]:
import google.generativeai as genai

genai.configure(api_key="Use Your API key")

for model in genai.list_models():
    if "generateContent" in model.supported_generation_methods:
        print(model.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-4-26b-a4b-it
models/gemma-4-31b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-3-pro-preview
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3.1-flash-lite
models/gemini-3-pro-image-preview
models/gemini-3-pro-image
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/gemini-3.1-flash-image
models/gemini-3.1-flash-lite-image
models/gemini-3.5-flash
models/gemini-3.5-flash-lite
models/gemini-omni-flash-preview
models/gemini-3.6-flash
models/lyria-3-clip-preview
models/lyria-3-pro-preview
models/gemini-3.1-flash-tts-preview
models/gemini-robotics-er-1.5-preview
models/gemini-robotics-er-1.6-preview
models/gemini-2.5-computer-use-preview-10-2025
models/antigravity-preview-05-2026
models/deep-research-max-preview-04-2026
models/deep-research-preview-04-2026
models/deep-research-pro-preview-12-2025

Top Complaint Keywords

late
broken
refund
damaged
support
delivery
quality

Top Complaint Keywords

late
broken
refund
damaged
support
delivery
quality

AI Generated Response 1

<email>

AI Generated Response 2

<email>

AI Generated Response 3

<email>

# README.md

# Customer Feedback Analysis and Automated Response

## Objective

Analyze customer reviews using Python and generate AI-powered apology emails.

## Dataset

Amazon Reviews Dataset

## Steps

1. Load dataset
2. Clean missing values
3. Clean review text
4. Filter ratings <=2
5. Find complaint keywords
6. Select top 3 detailed reviews
7. Generate apology emails using Google Gemini

## Libraries

- pandas
- numpy
- re
- collections
- google-generativeai

## Running

Install dependencies

pip install pandas numpy google-generativeai

Add your Gemini API Key inside the notebook.

Run all notebook cells.